version: '3.8'

services:
  app:
    build: .
    volumes:
      - "code:/var/www/app"
  nginx:
    image: nginx:latest
    volumes:
      - "./docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "code:/var/www/app:ro"
    depends_on:
      - app

volumes:
  code:
