##
# Template for development
##
version: '3.7'

services:
  app:
    build:
      target: dev
    hostname: app
    environment:
      - APP_ENV=dev

      # enable debugger
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
      # setting the server name for PhpStorm may be useful for debugging
      - PHP_IDE_CONFIG=serverName=symfony-docker-skeleton
  nginx:
    hostname: nginx
    ports:
      - "80:80"

volumes:
  code:
    driver: local

    # Connects to the docker host via nfs;
    # works with cifs on windows and local mapping on linux, as well;
    # adust to your needs.
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":$PWD"
